import { redirect } from "next/navigation";
import { loginAction } from "@/app/login/actions";
import { getCurrentUser } from "@/server/auth/current-user";
export const dynamic = "force-dynamic";
export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; email?: string; next?: string }> }) {
  const [params, user] = await Promise.all([searchParams, getCurrentUser()]);
  if (user) redirect(user.mustChangePassword ? "/account/password" : "/");
  return <main className="flex min-h-screen items-center justify-center bg-slate-950 px-6 py-12"><div className="w-full max-w-md"><div className="mb-8 text-center text-white"><p className="text-sm font-bold uppercase tracking-[0.3em] text-amber-400">CoffeeHQ</p><h1 className="mt-3 text-4xl font-bold">CoffeeOS</h1><p className="mt-3 text-slate-300">Sign in to your claim workspace.</p></div><section className="rounded-3xl bg-white p-7 shadow-2xl"><h2 className="text-2xl font-bold text-slate-950">Welcome back</h2><p className="mt-2 text-sm text-slate-600">Use the account created by your CoffeeHQ administrator.</p>{params.error ? <p className="mt-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{params.error}</p> : null}<form action={loginAction} className="mt-6 space-y-5"><input type="hidden" name="next" value={params.next ?? "/"}/><label className="block"><span className="text-sm font-semibold text-slate-700">Email address</span><input required autoComplete="email" type="email" name="email" defaultValue={params.email ?? ""} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><label className="block"><span className="text-sm font-semibold text-slate-700">Password</span><input required autoComplete="current-password" type="password" name="password" className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/></label><button className="w-full rounded-xl bg-amber-400 px-5 py-3 font-bold text-slate-950 hover:bg-amber-300">Sign in</button></form></section></div></main>;
}
